// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkhHsqNoHfDDm1u1-3LxIKYNNd_Jlutoo',
    appId: '1:1099107531397:web:b23ba7bef8f3a60d0987ec',
    messagingSenderId: '1099107531397',
    projectId: 'fakebook-f1abd',
    authDomain: 'fakebook-f1abd.firebaseapp.com',
    storageBucket: 'fakebook-f1abd.appspot.com',
    measurementId: 'G-KX6MZS6VXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2RfoIJkbOCbnRkv2DTHVg4DPzfxKq5Ls',
    appId: '1:1099107531397:android:400e8f1725d110a80987ec',
    messagingSenderId: '1099107531397',
    projectId: 'fakebook-f1abd',
    storageBucket: 'fakebook-f1abd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxC3oSiYMCLooOoDJdPS8SV5Sr_J1GgAk',
    appId: '1:1099107531397:ios:08b41ad4ceee5c0d0987ec',
    messagingSenderId: '1099107531397',
    projectId: 'fakebook-f1abd',
    storageBucket: 'fakebook-f1abd.appspot.com',
    iosClientId: '1099107531397-sbmv089jphlbrim25rihvdvdql5thjkl.apps.googleusercontent.com',
    iosBundleId: 'com.example.fakebookFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxC3oSiYMCLooOoDJdPS8SV5Sr_J1GgAk',
    appId: '1:1099107531397:ios:08b41ad4ceee5c0d0987ec',
    messagingSenderId: '1099107531397',
    projectId: 'fakebook-f1abd',
    storageBucket: 'fakebook-f1abd.appspot.com',
    iosClientId: '1099107531397-sbmv089jphlbrim25rihvdvdql5thjkl.apps.googleusercontent.com',
    iosBundleId: 'com.example.fakebookFrontend',
  );
}
